---
name: Build qnapsmsc

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          make test

      - id: go
        name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: |
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qnapsmsc
          path: bin/qnapsmsc
          retention-days: 30
